# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/micha/led_system/led_system.srcs/sources_1/bd/led_system/ip/led_system_proc_sys_reset_0_0/led_system_proc_sys_reset_0_0.xci
# IP: The module: 'led_system_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/micha/led_system/led_system.gen/sources_1/bd/led_system/ip/led_system_proc_sys_reset_0_0/led_system_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/micha/led_system/led_system.gen/sources_1/bd/led_system/ip/led_system_proc_sys_reset_0_0/led_system_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/micha/led_system/led_system.srcs/sources_1/bd/led_system/ip/led_system_proc_sys_reset_0_0/led_system_proc_sys_reset_0_0.xci
# IP: The module: 'led_system_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/micha/led_system/led_system.gen/sources_1/bd/led_system/ip/led_system_proc_sys_reset_0_0/led_system_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/micha/led_system/led_system.gen/sources_1/bd/led_system/ip/led_system_proc_sys_reset_0_0/led_system_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_system_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
