# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led_system_contraints.xdc

# Block Designs: bd/led_system/led_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_system || ORIG_REF_NAME==led_system} -quiet] -quiet

# IP: bd/led_system/ip/led_system_led_controller_0_0/led_system_led_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_system_led_controller_0_0 || ORIG_REF_NAME==led_system_led_controller_0_0} -quiet] -quiet

# IP: bd/led_system/ip/led_system_processing_system7_0_0/led_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_system_processing_system7_0_0 || ORIG_REF_NAME==led_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/led_system/ip/led_system_proc_sys_reset_0_0/led_system_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_system_proc_sys_reset_0_0 || ORIG_REF_NAME==led_system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/led_system/ip/led_system_axi_smc_0/led_system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_system_axi_smc_0 || ORIG_REF_NAME==led_system_axi_smc_0} -quiet] -quiet

# XDC: c:/Users/micha/led_system/led_system.gen/sources_1/bd/led_system/led_system_ooc.xdc
